import { Product } from '../components/ProductCard';
import Blazer from '../illustrations/Blazer';

export const PRODUCTS: Product[] = [
  {
    ProductId: 1,
    ProductName: 'Classic Blazer',
    ProductRate: 1999.0,
    ProductImage: '', // Not used
    ProductDescription: 'A stylish classic blazer for all occasions.',
    //category: 'men',
  },
  {
    ProductId: 2,
    ProductName: 'Blue Denim Jeans',
    ProductRate: 499.0,
    ProductImage: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=400&q=80',
    ProductDescription: 'Comfortable and stylish blue denim jeans.',
    //category: 'men',
  },
  {
    ProductId: 3,
    ProductName: 'Red Hoodie',
    ProductRate: 399.0,
    ProductImage: 'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&w=400&q=80',
    ProductDescription: 'Warm and cozy hoodie for chilly days.',
    //category: 'men',
  },
  {
    ProductId: 4,
    ProductName: 'Black Leather Jacket',
    ProductRate: 1299.0,
    ProductImage: 'https://images.unsplash.com/photo-1469398715555-76331a6c7c9b?auto=format&fit=crop&w=400&q=80',
    ProductDescription: 'Premium black leather jacket for a bold look.',
    //category: 'men',
  },
  {
    ProductId: 5,
    ProductName: 'Summer Dress',
    ProductRate: 349.0,
    ProductImage: 'https://images.unsplash.com/photo-1512436991641-6745cdb1723f?auto=format&fit=crop&w=400&q=80',
    ProductDescription: 'Light and breezy dress for summer days.',
    //category: 'women',
  },
  {
    ProductId: 6,
    ProductName: 'Striped Polo Shirt',
    ProductRate: 299.0,
    ProductImage: 'https://images.unsplash.com/photo-1515378791036-0648a3ef77b2?auto=format&fit=crop&w=400&q=80',
    ProductDescription: 'Casual striped polo, perfect for weekends.',
    //category: 'men',
  },
  {
    ProductId: 7,
    ProductName: 'Khaki Chinos',
    ProductRate: 449.0,
    ProductImage: 'https://images.unsplash.com/photo-1526178613658-3f1622045557?auto=format&fit=crop&w=400&q=80',
    ProductDescription: 'Versatile khaki chinos for work or play.',
    //category: 'men',
  },
  {
    ProductId: 8,
    ProductName: 'Floral Maxi Dress',
    ProductRate: 599.0,
    ProductImage: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=400&q=80',
    ProductDescription: 'Elegant floral maxi dress for special occasions.',
    //category: 'women',
  },
  {
    ProductId: 9,
    ProductName: 'Grey Sweatpants',
    ProductRate: 249.0,
    ProductImage: 'https://images.unsplash.com/photo-1512436991641-6745cdb1723f?auto=format&fit=crop&w=400&q=80',
    ProductDescription: 'Super soft sweatpants for lounging or gym.',
    //category: 'children',
  },
  {
    ProductId: 10,
    ProductName: 'Denim Shorts',
    ProductRate: 199.0,
    ProductImage: 'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&w=400&q=80',
    ProductDescription: 'Cool and comfy denim shorts for summer.',
    //category: 'children',
  },
  {
    ProductId: 11,
    ProductName: 'Checked Casual Shirt',
    ProductRate: 349.0,
    ProductImage: 'https://images.unsplash.com/photo-1469398715555-76331a6c7c9b?auto=format&fit=crop&w=400&q=80',
    ProductDescription: 'Trendy checked shirt for a smart look.',
    //category: 'men',
  },
  {
    ProductId: 12,
    ProductName: 'Basic Black Cap',
    ProductRate: 99.0,
    ProductImage: 'https://images.unsplash.com/photo-1515378791036-0648a3ef77b2?auto=format&fit=crop&w=400&q=80',
    ProductDescription: 'Classic black cap to complete your outfit.',
    //category: 'men',
  },
  {
    ProductId: 13,
    ProductName: 'White Sneakers',
    ProductRate: 799.0,
    ProductImage: 'https://images.unsplash.com/photo-1526178613658-3f1622045557?auto=format&fit=crop&w=400&q=80',
    ProductDescription: 'Comfortable and stylish white sneakers.',
    //category: 'men',
  },
  {
    ProductId: 14,
    ProductName: 'Blue Kurta',
    ProductRate: 399.0,
    ProductImage: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=400&q=80',
    ProductDescription: 'Traditional blue kurta for festive occasions.',
    //category: 'men',
  },
  {
    ProductId: 15,
    ProductName: 'Beige Cardigan',
    ProductRate: 499.0,
    ProductImage: 'https://images.unsplash.com/photo-1512436991641-6745cdb1723f?auto=format&fit=crop&w=400&q=80',
    ProductDescription: 'Soft beige cardigan for layering.',
    //category: 'women',
  },
];

export const numColumns = 2; 